Add a new http3 test server that always rejects zero rtt
mozilla/neqo pull request #1064
Opened 2020-12-14 21:11 UTC by KershawChang

This patch simply adds `disallow_zerortt_server` to facilitate 0-Rtt reject test.

2020-12-14 23:24 UTC, martinthomson requested changes
If you are looking to implement rejection of 0-RTT for neqo-server, then the implementation of the rejection code should be local to that file.

2020-12-14 23:24 UTC, martinthomson commented on neqo-transport/src/connection/tests/mod.rs
> +pub fn disallow_zerortt_server() -> Connection {
One-off things like this don't need functions to be added to the base fixture.  Just include this stuff inline.

2020-12-14 23:24 UTC, martinthomson commented on neqo-transport/src/connection/tests/zerortt.rs
> -    let mut server = Connection::new_server(
This is a different test case.  I would prefer that you add a new test case for your new thing.

2020-12-14 23:24 UTC, martinthomson commented on neqo-crypto/src/agent.rs
> +impl ZeroRttChecker for DisallowZeroRtt {
This doesn't need to be public.  There is no situation, except for testing, where you would enable 0-RTT but then reject it.

2021-06-21 20:26 UTC, ddragana commented
This has bin resolved by #1150

2021-06-21 20:26 UTC, closed without merging