Mark WebTransport streams keep alive
mozilla/neqo pull request #1389
Opened 2022-12-01 11:39 UTC by MayyaSunil

This PR is intended to resolve #1369

2022-12-01 14:05 UTC, martinthomson requested changes
See my comments on the issue.

2022-12-07 22:56 UTC, martinthomson requested changes
I don't think you have the right places for these calls.

You need one for the server and one for the client.

I think that the client one goes [in webtransport_create_session](https://github.com/mozilla/neqo/blob/b045c4a7033feffb133d05f86acea74dc50084ec/neqo-http3/src/connection.rs#L1054) and the server one goes [in webtransport_accept_session](https://github.com/mozilla/neqo/blob/b045c4a7033feffb133d05f86acea74dc50084ec/neqo-http3/src/connection.rs#L1098).

The points you have identified are about streams created within the session, not the session stream.

Finally, I would like to see test cases for this, showing that keep-alives (PING) are sent if the connection is left to go idle for too long, with only a webtransport session active.  There are test cases for keep-alive that you can base this on.

2024-02-07 07:51 UTC, larseggert commented
@MayyaSunil are you still intending to land this change?

2024-04-09 11:36 UTC, larseggert commented
@MayyaSunil any update on when you might get to this?

2024-04-11 08:56 UTC, MayyaSunil commented
> @MayyaSunil any update on when you might get to this?

I will resume this early next week and hope to complete by the end of the week

2024-04-15 05:48 UTC, larseggert commented
OK. Making this a draft PR until it's ready for review, please change it back then.

2024-04-19 12:44 UTC, larseggert commented
@MayyaSunil is this good to go functionality-wise? Does it still need a test?

2024-04-19 12:54 UTC, MayyaSunil commented
@larseggert Its not okay functionality wise and needs a test

2024-12-03 13:45 UTC, larseggert commented
CC @jesup

2024-12-03 16:22 UTC, larseggert commented
Webtransport newbie here. Trying to help wrap this up.

> I think that the client one goes [in webtransport_create_session](https://github.com/mozilla/neqo/blob/b045c4a7033feffb133d05f86acea74dc50084ec/neqo-http3/src/connection.rs#L1054)

The call to `create_bidi_transport_stream` in that function already enabled keepalives. Hence, are we done for the client?

> and the server one goes [in webtransport_accept_session](https://github.com/mozilla/neqo/blob/b045c4a7033feffb133d05f86acea74dc50084ec/neqo-http3/src/connection.rs#L1098).

I've made that addition, and added a test. WDYT?

2024-12-05 12:05 UTC, KershawChang approved these changes
This looks good to me.
Thanks!

2024-12-05 12:42 UTC, mxinden approved these changes
For what my review is worth, this looks good to me.

2024-12-05 12:42 UTC, mxinden commented on neqo-http3/tests/webtransport.rs
> +    assert_eq!(server.process_output(now()).callback(), idle_timeout / 2);
```suggestion
    // Expect client and server to send PING after half of the idle timeout in order to keep connection alive.
    assert_eq!(client.process_output(now()).callback(), idle_timeout / 2);
    assert_eq!(server.process_output(now()).callback(), idle_timeout / 2);
```

Feel free to ignore.

2024-12-10 11:14 UTC, larseggert commented
@martinthomson could you clear your old review, or better yet re-review?

2024-12-11 04:06 UTC, martinthomson approved these changes
This is certainly a lot cleaner than I remember it being.

2024-12-11 04:18 UTC, merged