benchmarks for coalesce/mark_range
mozilla/neqo pull request #1592
Opened 2024-01-26 20:58 UTC by jesup

2024-01-29 00:42 UTC, martinthomson reviewed
See #1594 for a few updates on this benchmark that should make it a little nicer.

2024-02-01 15:44 UTC, larseggert requested changes

2024-02-01 15:44 UTC, larseggert commented on neqo-transport/src/lib.rs
> +pub mod send_stream;
See how @martinthomson does it here with a new feature: https://github.com/mozilla/neqo/pull/1594/files#diff-ea9df8dd0e492efc27d0690a0529971f8debe8ff01291cee81ca7db8ab1e6465R31-R33

2024-02-01 15:44 UTC, larseggert commented on neqo-transport/src/send_stream.rs
> +pub enum RangeState {
Might use the same trick here and below where `pub` is added.

2024-02-06 07:00 UTC, closed without merging