Coalesce better
mozilla/neqo pull request #1594
Opened 2024-01-29 00:37 UTC by martinthomson

@jesup this is a version of your patch that looks worse on the bench, but I think that it is concretely better.

The bench you created sets up with N abutting acknowledged ranges.  The current code coalesces just one of them when it fills in the gap.  This patch coalesces all of them.  The result is a benchmark regression (and a noticeable one) when there are more entries.  But that is the risk of having microbenchmarks.  They don't measure what really matters.  I think that this change will ensure less thrashing.

<details>
<summary>Results</summary>

```
coalesce_acked_from_zero 2 entries
                        time:   [61.129 ns 61.278 ns 61.476 ns]
                        change: [-48.216% -48.086% -47.935%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  1 (1.00%) low severe
  1 (1.00%) low mild
  4 (4.00%) high severe

coalesce_acked_from_zero 100 entries
                        time:   [710.17 ns 710.94 ns 711.66 ns]
                        change: [+304.53% +306.46% +308.06%] (p = 0.00 < 0.05)
                        Performance has regressed.

coalesce_acked_from_zero 1000 entries
                        time:   [1.5435 µs 1.5450 µs 1.5467 µs]
                        change: [+593.07% +594.29% +595.49%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```
</details>

2024-01-30 06:23 UTC, martinthomson commented
Looking at the build failures here, the windows ones look unrelated, but troubling.  The mac one looks transient as the latest stable toolchain couldn't be downloaded.

2024-01-30 07:47 UTC, larseggert commented
Do you maybe need to change `neqo-crypto/Cargo.toml` similarly to `neqo-transport/Cargo.toml`, i.e., add the `bench` stuff? (Just guessing.)

2024-02-02 03:04 UTC, jesup commented on neqo-transport/benches/range_tracker.rs
> +                used.mark_acked(tail, CHUNK as usize);
What exactly is this supposed to be doing?  
'used' is modified, and then reused in the modified state in the next iteration, etc.
After the first iteration, it keeps re-marking CHUNK to CHUNK+CHUNK-1 as acked, though they're already acked.
Unfortunately, if you restore the 'used' to the original state, or (re)clone it, that will be included in the time for the benchmark, and given cloning or restoring probably mean allocations, that may swamp the coalesce function.
I have a question in the criterion maintainers about if there's a way to have a per-iteration setup function that's not  included in the measurement

2024-02-02 03:14 UTC, jesup commented on neqo-transport/benches/range_tracker.rs
> +                used.mark_acked(tail, CHUNK as usize);
We could build an vector of N copies of the input, and then limit iterations to N.  I'm not finding any other good options

2024-02-02 03:16 UTC, jesup commented on neqo-transport/benches/range_tracker.rs
> +                used.mark_acked(tail, CHUNK as usize);
https://docs.rs/criterion/latest/criterion/struct.Bencher.html#method.iter_batched_ref should do it

2024-02-05 07:31 UTC, larseggert requested changes
@martinthomson could we separate the bench from the perf improvement into two different PRs? That would allow to see the performance improvement. (And might also give us some idea of what exactly makes the Windows linking fail.)

2024-02-07 12:11 UTC, larseggert commented
@martinthomson when you have a chance, would you resolve the conflicts and get this ready to land?

2024-02-08 06:46 UTC, larseggert approved these changes

2024-02-08 06:46 UTC, merged