Maybe make the timer wheel faster
mozilla/neqo pull request #1763
Opened 2024-03-20 03:16 UTC by martinthomson

CHECK THE BENCHMARKS

2024-03-20 05:05 UTC, larseggert commented
@martinthomson could you make clippy happy, so the benches run?

2024-03-21 00:58 UTC, larseggert commented
@martinthomson I think we need a microbenchmark or two to see if this makes a difference.

2024-03-22 21:52 UTC, martinthomson commented
The microbenchmark I added improves by a third.

2024-03-22 23:36 UTC, larseggert requested changes
You probably need to rebase this off `main`.

2024-03-22 23:36 UTC, larseggert commented on neqo-crypto/bindings/bindings.toml
> -enums = ["mozilla::pkix::ErrorCode"]
Seems unrelated?

2024-03-22 23:36 UTC, larseggert commented on neqo-crypto/src/err.rs
> +    }
Seems unrelated? I think you may have based your PR off a different branch than `main`?

2024-03-25 00:37 UTC, martinthomson commented
```
     Running benches/timer.rs (target/release/deps/timer-acd3fe64661c7be7)
drain a timer quickly   time:   [139.34 ns 148.51 ns 157.44 ns]
                        change: [-71.072% -69.916% -68.575%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
  12 (12.00%) high mild
  3 (3.00%) high severe
```

That's not a one third improvement, that is this taking one third of the original.  So a more than 3x speed up.

2024-03-25 06:16 UTC, larseggert approved these changes

2024-03-25 06:33 UTC, merged