bench(transfer): run with and without pacing
mozilla/neqo pull request #2006
Opened 2024-07-24 09:23 UTC by mxinden

Might help debug https://github.com/mozilla/neqo/pull/1998.

Does reproduce regression described in https://github.com/mozilla/neqo/pull/1998.

2024-07-24 11:48 UTC, KershawChang approved these changes

2024-07-24 15:33 UTC, larseggert requested changes
We need a fix to the action/workflow that unbreaks the results reporting.

2024-07-24 23:49 UTC, larseggert approved these changes

2024-07-25 00:13 UTC, merged

2024-07-26 15:46 UTC, mxinden commented on .github/workflows/bench.yml
> +            perl -p -0777 -e 's/(.*?)\n(.*?)(((No change|Change within|Performance has).*?)(\nFound .*?)?)?\n\n/<details><summary>$1: $4<\/summary><pre>\n$2$5$6<\/pre><\/details>\n/gs' |\
Thank you @larseggert!